// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKi7KD4awMV6BGODG7apLkm6ueZ_yqKo',
    appId: '1:359764588507:web:62e505ead84a8b64d259fe',
    messagingSenderId: '359764588507',
    projectId: 'vetconnect-ab69b',
    authDomain: 'vetconnect-ab69b.firebaseapp.com',
    storageBucket: 'vetconnect-ab69b.firebasestorage.app',
    measurementId: 'G-ZW1ZRRSEYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKDzbR68TkgUuFiVTSEfQHMGKOdd4PUA',
    appId: '1:359764588507:android:e7c021381e17e7cfd259fe',
    messagingSenderId: '359764588507',
    projectId: 'vetconnect-ab69b',
    storageBucket: 'vetconnect-ab69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdiSG-BTynhSILrkiajs_qQ4tXRgKrrl8',
    appId: '1:359764588507:ios:42cf34074f545cf0d259fe',
    messagingSenderId: '359764588507',
    projectId: 'vetconnect-ab69b',
    storageBucket: 'vetconnect-ab69b.firebasestorage.app',
    iosBundleId: 'com.example.vetconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdiSG-BTynhSILrkiajs_qQ4tXRgKrrl8',
    appId: '1:359764588507:ios:42cf34074f545cf0d259fe',
    messagingSenderId: '359764588507',
    projectId: 'vetconnect-ab69b',
    storageBucket: 'vetconnect-ab69b.firebasestorage.app',
    iosBundleId: 'com.example.vetconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsKi7KD4awMV6BGODG7apLkm6ueZ_yqKo',
    appId: '1:359764588507:web:3e853cd4207353cad259fe',
    messagingSenderId: '359764588507',
    projectId: 'vetconnect-ab69b',
    authDomain: 'vetconnect-ab69b.firebaseapp.com',
    storageBucket: 'vetconnect-ab69b.firebasestorage.app',
    measurementId: 'G-ZZCYJ0ZTG6',
  );
}
